### PR TITLE
Some changes for Linux and Windows users.

### PR DESCRIPTION
**Pull request by ppamorim**

### CODE REVIEW

**Comment by konifar** [comment]
Thank you for your document fix! This fix will be helpful for a lot of users.

**Comment by konifar** [comment]
@ppamorim There's something I need to ask you. Do you use Windows or Linux machines?
In fact, I don't have both machines, and cannot check this plugin work properly...

**Comment by ppamorim** [comment]
@konifar Linux

**Comment by konifar** [comment]
@ppamorim Thank you for your reply :+1:

**Pull request merged**
