### PR TITLE
Fixed issues in Windows. Cleaned up workspace folders.

### PR DESCRIPTION
**Pull request by ahornerr**
I apologize for the giant change log, I removed the `out/` folder from the repository.

This should fix issues #1, #2, #5, #6, #7, #17. As a convenience, I've also re-build the new .jar from my source.

### CODE REVIEW

**Comment by mateusz-szafraniec** [comment]
Another NPE...
Win8.1/64bit
java.lang.NullPointerException
    at java.io.FileInputStream.<init>(FileInputStream.java:130)
    at com.intellij.openapi.util.JDOMUtil.loadDocument(JDOMUtil.java:337)
    at com.konifar.material_icon_generator.MaterialDesignIconGenerateDialog.initIconComboBox(MaterialDesignIconGenerateDialog.java:382)
    at com.konifar.material_icon_generator.MaterialDesignIconGenerateDialog.<init>(MaterialDesignIconGenerateDialog.java:100)
    at com.konifar.material_icon_generator.MaterialDesignIconGenerateAction.actionPerformed(MaterialDesignIconGenerateAction.java:27)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ahornerr** [comment]
@mateusz-szafraniec It looks like you aren't using the latest version of the plugin. Please try the following:
- Remove the old plugin from Android Studio
- Restart Android Studio
- Re-download the .jar from my fork (https://github.com/ahornerr/android-material-design-icon-generator-plugin/blob/master/MaterialDesignIconGeneratorPlugin.jar?raw=true)
- Install the downloaded jar via Android Studio
  - If this step was successful, you should see version 1.3 of the plugin in Android Studio
- Restart Android Studio again

At this point the plugin should be working for you.

**Comment by mateusz-szafraniec** [comment]
It works - thanks !

**Comment by ahornerr** [comment]
@mateusz-szafraniec Great, I'm glad I could help :)

**Comment by konifar** [comment]
@ahornerr Thanks for your great fix! I'll check it!! :)

**Comment by ahornerr** [comment]
I added a partial fix for #23 - automatic resource directory resolution.

**Comment by konifar** [comment]
@ahornerr Your branch has some errors.
`org.jetbrains.android` package is nothing. I don't know why... Can you know the reason?

``` java
import org.jetbrains.android.facet.AndroidFacet;
import org.jetbrains.android.util.AndroidUtils;
```

**Comment by ahornerr** [comment]
@konifar To get the automatic resource resolution working, I had to import the android.jar library into the Intellij project. I was able to find this at the path `<Android Studio Root>/plugins/android/lib/android.jar` on my Windows machine. When releasing the plugin, this jar is not required to be packaged along with the plugin jar (as it is included in Android Studio). Here is what my Intellij project settings look like:

**Comment by konifar** [comment]
@ahornerr Thank you for your detailed information. I'll try it :)

**Comment by ahornerr** [comment]
@konifar Sure, no problem! Thanks for creating such an awesome plugin.

**Comment by konifar** [comment]
@ahornerr Thank you! It works. I checked and upload new plugin to IntelliJ plugin center. So after few days, new version which contains your great fix will be released.

**Comment by ahornerr** [comment]
Thank you very much. Would this include the resource directory resolution? Unfortunately I haven't had time to refine it (for multiple resource directories) but it should work in 90% of cases.

**Pull request merged**
