### PR TITLE
added custom colors

### PR DESCRIPTION
**Pull request by ktomek**
- added custom colors
- added material design color palette

zrzut ekranu 2015-02-27 o 22 22 34

### CODE REVIEW

**Comment by konifar** [comment]
@ktomek Thank you for your great feature! I'll check this pull request.

**Comment by goncalossilva** [comment]
:+1:

**Comment by QuadFlask** [comment]
:+1:

**Comment by konifar** [comment]
I merged this pull request, and fix little bugs.
I already release new version. After 3~5 days, you can use this custom color function.
Thanks your help!

**Comment by konifar** [comment]
Now new version is approved, you can update and use this feature.

**Pull request merged**
